### ISSUE TITLE
Page Property query fails within the renderer

### ISSUE THREAD

**Issue by adxsoft** [QWxleA/logseq-cuvee#5]
This query `{{query (page-property type "expense")}}` gives me 21 results

`{{renderer :cuvee, true, (page-property type "expense")}}` 
- shows nothing
- no Preview or export Button

Looks like it does not handle the "expense" literal in the page-property

![Screen Shot 2022-08-15 at 11 44 00 pm](https://user-images.githubusercontent.com/24862237/184647007-fddefcda-9d25-4033-8026-1c30ed499065.png)

**Comment by adxsoft** [comment]
I'm running on a Mac OSX High Sierra and Logseq 0.7.6

**Comment by todrobbins** [comment]
@adxsoft I was just testing this on my end, and it seems the issue is that it's not parsing the `"`. So the same query without quotes works without a hitch. I think the query language doesn't support the quotes.
